# Generated by Django 5.0.4 on 2024-06-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0001_initial'),
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='continente_pais',
            field=models.ManyToManyField(to='pais.pais'),
        ),
    ]
