# Generated by Django 5.0.4 on 2024-06-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0003_remove_continente_continente_pais_continente_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continente',
            name='pais',
        ),
    ]
