# Generated by Django 5.0.4 on 2024-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0004_remove_continente_pais'),
        ('pais', '0010_remove_pais_continente'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='pais',
            field=models.ManyToManyField(related_name='continentes', to='pais.pais'),
        ),
    ]
