# Generated by Django 5.0.4 on 2024-06-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0005_continente_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continente',
            name='pais',
        ),
    ]
