# Generated by Django 5.0.4 on 2024-06-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('pais', '0006_remove_pais_pais_ciudad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
