# Generated by Django 5.0.4 on 2024-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudad', '0002_delete_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_posta', models.CharField(max_length=5, unique=True, verbose_name='Codigo postal')),
                ('nombre_ciudad', models.CharField(max_length=20, unique=True, verbose_name='Nombre ciudad')),
                ('descripcion_ciudad', models.CharField(max_length=50, verbose_name='Descripcion ciudad')),
            ],
        ),
    ]
