# Generated by Django 5.0.4 on 2024-06-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0004_ciudad_pais'),
        ('pais', '0010_remove_pais_continente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='pais.pais'),
        ),
    ]
