# Generated by Django 5.0.4 on 2024-06-09 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0001_initial'),
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='idioma_pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pais.pais'),
        ),
    ]
