# Generated by Django 5.0.4 on 2024-06-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0002_idioma_idioma_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='idioma_pais',
        ),
        migrations.AlterField(
            model_name='idioma',
            name='codigoIdioma',
            field=models.CharField(max_length=10, verbose_name='Codigo Idioma'),
        ),
    ]
