# Generated by Django 5.0.4 on 2024-06-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_remove_idioma_idioma_pais_alter_idioma_codigoidioma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idioma',
            old_name='codigoIdioma',
            new_name='codigo_idioma',
        ),
        migrations.RenameField(
            model_name='idioma',
            old_name='nombreIdioma',
            new_name='nombre_idioma',
        ),
    ]
