# Generated by Django 5.0.4 on 2024-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_remove_idioma_idioma_pais_alter_idioma_codigoidioma'),
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='pais_idioma',
            field=models.ManyToManyField(to='idioma.idioma'),
        ),
    ]
