# Generated by Django 5.0.4 on 2024-06-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_remove_idioma_idioma_pais_alter_idioma_codigoidioma'),
        ('pais', '0002_pais_pais_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='prueba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prueba_pais', to='idioma.idioma'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_idioma',
            field=models.ManyToManyField(related_name='pais_idioma', to='idioma.idioma'),
        ),
    ]
