# Generated by Django 5.0.4 on 2024-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_remove_idioma_idioma_pais_alter_idioma_codigoidioma'),
        ('pais', '0003_pais_prueba_alter_pais_pais_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='prueba',
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_idioma',
            field=models.ManyToManyField(to='idioma.idioma'),
        ),
    ]
