# Generated by Django 5.0.4 on 2024-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('pais', '0004_remove_pais_prueba_alter_pais_pais_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='pais_ciudad',
            field=models.ManyToManyField(to='ciudad.ciudad'),
        ),
    ]
