# Generated by Django 5.0.4 on 2024-06-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0005_pais_pais_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='pais_ciudad',
        ),
    ]
