# Generated by Django 5.0.4 on 2024-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_remove_idioma_idioma_pais_alter_idioma_codigoidioma'),
        ('pais', '0007_pais_pais_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='codigoPais',
            new_name='codigo_pais',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombrePais',
            new_name='nombre_pais',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='pais_ciudad',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='pais_idioma',
        ),
        migrations.AddField(
            model_name='pais',
            name='idioma',
            field=models.ManyToManyField(related_name='paises', to='idioma.idioma'),
        ),
    ]
