# Generated by Django 5.0.4 on 2024-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0004_remove_continente_pais'),
        ('pais', '0008_rename_codigopais_pais_codigo_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='continente',
            field=models.ManyToManyField(related_name='paises', to='continente.continente'),
        ),
    ]
