# Generated by Django 5.0.4 on 2024-06-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0009_pais_continente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='continente',
        ),
    ]
